format = """
$directory\
$git_branch\
$git_status """

[directory]
style = "fg:#112330 bg:#ffe56e bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "󰘬"
style = "fg:#112330 bg:#f6aa6b bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#112330 bg:#ff6347 bold"
format = '[( $all_status$ahead_behind )]($style)'

