format = """
$directory\
$git_branch\
$git_status """

[directory]
style = "fg:#0c1b2a bg:#e0b547 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "󰘬"
style = "fg:#0c1b2a bg:#e58e44 bold"
format = '[ $symbol $branch ]($style)'
truncation_length = 8

[git_status]
style = "fg:#0c1b2a bg:#ff3d00 bold"
format = '[( $all_status$ahead_behind )]($style)'

