return {
  {
    "ibhagwan/fzf-lua",
    opts = {},
    keys = {
      {
        "<C-p>",
        function()
          require("fzf-lua").files()
        end,
      },
      {
        "gra",
        function()
          require("fzf-lua").lsp_code_actions()
        end,
      },
      {
        "grd",
        function()
          require("fzf-lua").lsp_definitions()
        end,
      },
      {
        "grr",
        function()
          require("fzf-lua").lsp_references()
        end,
      },
      {
        "gri",
        function()
          require("fzf-lua").lsp_implementations()
        end,
      },
      {
        "gO",
        function()
          require("fzf-lua").lsp_document_symbols()
        end,
      },
      {
        "<C-f>",
        function()
          require("fzf-lua").live_grep()
        end,
      },
      {
        "<C-f>",
        function()
          require("fzf-lua").grep_visual()
        end,
        mode = "v",
      },
      {
        "<leader><C-r>",
        function()
          require("fzf-lua").resume()
        end,
      },
    },
  },
}
